name: treyhope_dev
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  # walkdown:
  #   git: https://github.com/trey-a-hope/walkdown.git
  walkdown:
    path: /Users/treyhope/Desktop/Development/walkdown
  # flutter_lints: ^2.0.3
  jaspr: ^0.22.0
  jaspr_flutter_embed: ^0.4.10
  jaspr_router: ^0.8.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  flutter_test:
    sdk: flutter
  jaspr_builder: ^0.22.0
  lints: ^6.0.0

jaspr:
  mode: static
  flutter: embedded

flutter:
  uses-material-design: true
