name: treyhope_dev
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  animated_quiz_widget: ^1.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  google_fonts: ^6.1.0
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.8.1
  jaspr: ^0.22.0
  jaspr_flutter_embed: ^0.4.10
  jaspr_riverpod: ^0.4.2
  jaspr_router: ^0.8.1
  lucide_icons_flutter: ^3.1.8
  screenshot: ^3.0.0
  toastification: ^3.0.3
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4
  markdown: ^7.3.0
  universal_web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  jaspr_builder: ^0.22.0
  json_serializable: ^6.9.4
  lints: ^6.0.0

jaspr:
  mode: static
  flutter: embedded
 
  targets:
    - /
    - /about
    - /projects
    - /code-flows
    - /blog
    - /blog/coffee-code-jaspr-web-framework
    - /blog/coffee-code-nakama-secure-sessions
    - /blog/coffee-code-miro-user-flows
    - /blog/coffee-code-firestore-sorting-toasts
    - /blog/coffee-code-nakama-backend-servers
    - /blog/coffee-code-flutter-flame-mario
    - /blog/coffee-code-firebase-migration-authentication
    - /blog/coffee-code-book-quotes-updates
    - /blog/coffee-code-flutter-book-quotes
    - /blog/coffee-code-gift-grab-powerups
    - /blog/coffee-code-questionz-flutter-app
    - /blog/tags/jaspr
    - /blog/tags/dart
    - /blog/tags/webdev
    - /blog/tags/bulma
    - /blog/tags/seo
    - /blog/tags/nakama
    - /blog/tags/gamedev
    - /blog/tags/flutter
    - /blog/tags/authentication
    - /blog/tags/sessions
    - /blog/tags/miro
    - /blog/tags/ux
    - /blog/tags/userflows
    - /blog/tags/prototyping
    - /blog/tags/firestore
    - /blog/tags/riverpod
    - /blog/tags/toastmessages
    - /blog/tags/mobiledev
    - /blog/tags/docker
    - /blog/tags/backend
    - /blog/tags/flame
    - /blog/tags/tiled
    - /blog/tags/mobile
    - /blog/tags/firebase
    - /blog/tags/migration
    - /blog/tags/cloudFirestore
    - /blog/tags/database
    - /blog/tags/bookquotes
    - /blog/tags/mobileapp
    - /blog/tags/uidesign
    - /blog/tags/animations
    - /blog/tags/books
    - /blog/tags/quotes
    - /blog/tags/reading
    - /blog/tags/gamedevelopment
    - /blog/tags/powerups
    - /blog/tags/appstore
    - /blog/tags/giftgrab
    - /blog/tags/graphql
    - /blog/tags/mongodb
    - /blog/tags/appdevelopment

flutter:
  uses-material-design: true